# -*- coding: utf-8 -*-
"""code 01_intro.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qctLPcrFzXx4nYuyYocEfL75vcfNRKIQ
"""

!pip install -Uqq fastbook

# below are typical python codes
#from fastbook import *

#setup_book()

# Cat-Dog Classifier
from fastai.vision.all import *

# URLs.PETS

# path = untar_data(URLs.PETS)/'images'
dest = untar_data(URLs.PETS)

type(dest)





# !ls -a /root/.fastai/data/oxford-iiit-pet/images/

# !cp -a /root/.fastai/data/oxford-iiit-pet/ /content/sample_data

# doc(untar_data)

# help(untar_data)

# type(dest)
# https://docs.python.org/3/library/pathlib.html

!ls /root/.fastai/data/oxford-iiit-pet/images

path = dest/'images'

path

# path

# !ls /root/

# !ls -a /root/

# !ls -a /root/.fastai/data/oxford-iiit-pet/images

def is_cat(x): return x[0].isupper()

is_cat("Hello")

is_cat("hello")

# Class method "ImageDataLoaders.from_name_func"
dls = ImageDataLoaders.from_name_func(
    path, get_image_files(path), valid_pct=0.2, seed=42,
    label_func=is_cat, item_tfms=Resize(224))

type(dls)

learn = cnn_learner(dls, resnet34, metrics=error_rate)

type(learn)

learn.fine_tune(2) # an instance method
# A learner object has a method called "fine_tune()"

doc(learn.fine_tune)

#!learn.export('/content/model.pkl')

from google.colab import drive
drive.mount('/content/drive')

#uploader = SimpleNamespace(data = ['images/chapter1_cat_example.jpg'])
uploader = SimpleNamespace(data = ['/content/drive/MyDrive/Colab Notebooks/data/images/cat.png'])
uploader2 = SimpleNamespace(data = ['/content/drive/MyDrive/Colab Notebooks/data/images/dog.jpg'])

type(uploader)

img = PILImage.create(uploader.data[0])
img.to_thumb(192)

# type(img)

img_tmp = Image.open(uploader.data[0])

type(img_tmp)

img_tmp

type(img_tmp)

is_cat,_,probs = learn.predict(img_tmp)

print(f"Is this a cat?: {is_cat}.")
print(f"Probability it's a cat: {probs[1].item():.6f}")

is_cat,_,probs = learn.predict(img)
#https://github.com/fastai/fastai/issues/3880

probs

print(f"Is this a cat?: {is_cat}.")
print(f"Probability it's a cat: {probs[1].item():.6f}")

#img2 = PILImage.create(uploader2.data[0])
img2 = Image.open(uploader2.data[0])
img2.to_thumb(192)

is_cat,_,probs = learn.predict(img2)
print(f"Is this a cat?: {is_cat}.")
print(f"Probability it's a cat: {probs[1].item():.6f}")

# We can make a copy of an image to one of oour visible folders
!cp /root/.fastai/data/oxford-iiit-pet/images/* /content/sample_data

# NLP example
from fastai.text.all import *

imdb = untar_data(URLs.IMDB)

URLs.IMDB

imdb

dls = TextDataLoaders.from_folder(imdb, valid='test')
learn = text_classifier_learner(dls, AWD_LSTM, drop_mult=0.5, metrics=accuracy)
learn.fine_tune(3, 1e-2)

learn.predict("I really liked that movie!")

learn.predict("This movie is bad.")

learn.predict("This movie is awesome.")

# Tabular dataset example
from fastai.tabular.all import *
path = untar_data(URLs.ADULT_SAMPLE)

dls = TabularDataLoaders.from_csv(path/'adult.csv', path=path, y_names="salary",
    cat_names = ['workclass', 'education', 'marital-status', 'occupation',
                 'relationship', 'race'],
    cont_names = ['age', 'fnlwgt', 'education-num'],
    procs = [Categorify, FillMissing, Normalize])

learn = tabular_learner(dls, metrics=accuracy)

dls.show()

learn.fit_one_cycle(3)

learn.show_results()

# Recommendation systems
from fastai.collab import *
path = untar_data(URLs.ML_SAMPLE)
dls = CollabDataLoaders.from_csv(path/'ratings.csv')
learn = collab_learner(dls, y_range=(0.5,5.5))
learn.fine_tune(10)

learn.show_results()